server:
  port: 8080

spring:
  application:
    name: api-gateway-develop

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://users-service-develop:8081
          predicates:
            - Path=/users/**

        - id: turnos-service
          uri: http://turnos-service-develop:8082
          predicates:
            - Path=/turnos/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"