spring.application.name=turnos-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/turnosdb
spring.datasource.username=postgres
spring.datasource.password=yeison

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.application.name=turnos-service