server.port=8182
spring.application.name=turnos-service-qa

spring.datasource.url=jdbc:postgresql://turnos-db-qa:5432/turnosdb_qa
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true